MKdisk -sizE=120 -fit=BF -unit=M -path=D1.dk
MKdisk -path=D2.dk -fit=BF -sizE=120 -unit=M 
MKdisk -sizE=120 -fit=BF -path=D3.dk
MKdisk -fit=BF -sizE=120 -unit=M 
MKdisk -path=D4.dk -size=150
fdisk -type=P -path=D1.dk -Unit=B -name=Particion2 -size=300
fdisk -size=100 -type=P -unit=B -fit=BF -path=D1.dk -name=Particion3
fdisk -size=100 -type=P -unit=B -fit=BF -path=D1.dk -name=Particion2
fdisk -size=100 -type=P -unit=B -fit=BF -path=D1.dk -name=Particion4

